
package com.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TesztWSService", targetNamespace = "http://example.com/", wsdlLocation = "http://10.0.12.16:8080/hello?wsdl")
public class TesztWSService
    extends Service
{

    private final static URL TESZTWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.jaxws.TesztWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.jaxws.TesztWSService.class.getResource(".");
            url = new URL(baseUrl, "http://10.0.12.16:8080/hello?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.12.16:8080/hello?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TESZTWSSERVICE_WSDL_LOCATION = url;
    }

    public TesztWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TesztWSService() {
        super(TESZTWSSERVICE_WSDL_LOCATION, new QName("http://example.com/", "TesztWSService"));
    }

    /**
     * 
     * @return
     *     returns TesztWS
     */
    @WebEndpoint(name = "TesztWSPort")
    public TesztWS getTesztWSPort() {
        return super.getPort(new QName("http://example.com/", "TesztWSPort"), TesztWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TesztWS
     */
    @WebEndpoint(name = "TesztWSPort")
    public TesztWS getTesztWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/", "TesztWSPort"), TesztWS.class, features);
    }

}
